<!DOCTYPE html >
<html lang="FR-fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/main.css">
    <title> Voiron Sport Auto </title>
</head>
<body>
<main>
    <header>
        <a href="../index.html">
            <img src="#" alt="Logo Voiron Sport Auto">
        </a>
    </header>
    <nav>
        <ul>
            <li>
                <a href="../index.html"> Accueil</a>
            </li>
            <li>
                <a href="../formulaireEvent/form_event.phtml"> Formulaire événement </a>
            </li>
            <li>
                <a href="../form_contact/form_contact.phtml"> Nous contacter </a>
            </li>
        </ul>
    </nav>
</main>
</body>
</html>

